### ISSUE TITLE
Issue on tie, on combination of feature 1, 2

### ISSUE THREAD

**Issue by SaraGhlm** [alirezagoli/tictactoe#5]
After combining feature 1 and 2. I noticed when there is a tie scoreboard gives an error as it does not check for the tie. I attached the stacktrace.

Exception in thread "main" java.lang.NullPointerException
	at cs.ualberta.cmput402.tictactoe.TicTacToeGame.playGame(TicTacToeGame.java:59)
	at cs.ualberta.cmput402.tictactoe.TicTacToeGame.main(TicTacToeGame.java:69)

**Comment by alirezagoli** [comment]
This bug is solved now.
